"""Agrego campo certificate_file a User6

Revision ID: 764bb14d9286
Revises: 9271058fda80
Create Date: 2025-10-26 15:35:38.295212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764bb14d9286'
down_revision = '9271058fda80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('subcategory', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('website')
        batch_op.drop_column('subcategory')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
