"""Agrego campo certificate_file a User3

Revision ID: 9271058fda80
Revises: ac381fbfdf63
Create Date: 2025-10-26 14:56:44.082418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9271058fda80'
down_revision = 'ac381fbfdf63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('registration_date')

    # ### end Alembic commands ###
